apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simpleapp-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: supply
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/dev/simpleapp
    repoURL: https://github.com/rudzm/managment
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true