apiVersion: v2
name: firstapp-main
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: app-deployment
  repository: https://raw.githubusercontent.com/rudzm/helm-charts-repo/main/
  version: 0.5.0
